# Generated by Django 5.2.7 on 2025-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0002_medico_delete_historialclinico_delete_vercitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
            preserve_default=False,
        ),
    ]
