# Generated by Django 5.2.7 on 2025-10-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0003_medico_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='nombre',
        ),
    ]
