# Generated by Django 5.2.7 on 2025-10-29 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Paciente', models.CharField(max_length=20)),
                ('A_Paciente', models.CharField(max_length=20)),
                ('DNI_Paciente', models.CharField(max_length=8)),
                ('descripcion', models.TextField(blank=True)),
                ('Fecha_Cita', models.DateTimeField(auto_now_add=True)),
                ('Hora_Cita', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
