# Generated by Django 5.2.7 on 2025-10-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre del paciente', models.CharField(max_length=20)),
                ('Apellido del paciente', models.CharField(max_length=20)),
                ('DNI', models.CharField(max_length=8)),
                ('Detalles de la cita', models.TextField(blank=True)),
                ('Fecha', models.DateTimeField(null=True)),
                ('Asignar Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
