# Generated by Django 5.2.7 on 2025-10-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0002_medico_delete_historialclinico_delete_vercitas'),
        ('P_Administrativo', '0002_crearcita_delete_crearcitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearcita',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crearcita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medico.medico'),
        ),
    ]
